version: '3.8'

services:
  snapshot:
    build: ${SNAPSHOT_REPO_PATH}
    ports:
      - "3002:3002"
    env_file:
      - ${SNAPSHOT_REPO_PATH}/.env
      - ./envs/.env.snapshot.local
    volumes:
      - ${SNAPSHOT_REPO_PATH}:/app
      - /app/node_modules
    command: yarn run vite --port=3002 --host
    depends_on:
      - snapshot-hub
      - snapshot-relayer
      - score-api

  snapshot-hub:
    build: ${SNAPSHOT_HUB_REPO_PATH}
    ports:
      - "3000:3000"
    env_file:
      - ${SNAPSHOT_HUB_REPO_PATH}/.env
      - ./envs/.env.snapshot-hub.local
    volumes:
      - ${SNAPSHOT_HUB_REPO_PATH}:/app
      - /app/node_modules
    depends_on:
      mysql:
        condition: service_healthy
      snapshot-sequencer:
        condition: service_started

  keycard:
    build: ${KEYCARD_REPO_PATH}
    ports:
      - "3005:3005"
    env_file:
      - ${KEYCARD_REPO_PATH}/.env
      - ./envs/.env.keycard.local
    volumes:
      - ${KEYCARD_REPO_PATH}:/app
      - /app/node_modules
    depends_on:
      mysql:
        condition: service_healthy

  snapshot-sequencer:
    build: ${SNAPSHOT_SEQUENCER_REPO_PATH}
    ports:
      - "3001:3001"
    env_file:
      - ./envs/.env.snapshot-sequencer.local
      - ${SNAPSHOT_SEQUENCER_REPO_PATH}/.env
    volumes:
      - ${SNAPSHOT_SEQUENCER_REPO_PATH}:/app
      - /app/node_modules
    depends_on:
      mysql:
        condition: service_healthy

  score-api:
    build: ${SCORE_API_REPO_PATH}
    ports:
      - "3003:3003"
    env_file:
      - ./envs/.env.score-api.local
      - ${SCORE_API_REPO_PATH}/.env
    volumes:
      - ${SCORE_API_REPO_PATH}:/app
      - /app/node_modules

  snapshot-relayer:
    build: ${SNAPSHOT_RELAYER_REPO_PATH}
    ports:
      - "3004:3004"
    env_file:
      - ./envs/.env.snapshot-relayer.local
      - ${SNAPSHOT_RELAYER_REPO_PATH}/.env
    volumes:
      - ${SNAPSHOT_RELAYER_REPO_PATH}:/app
      - /app/node_modules
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
      - ./schemas:/docker-entrypoint-initdb.d
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 10s
        retries: 10

volumes:
  mysql:
    driver: local
